backend/README.md

Set up the environment of the backend
Fixes # (issue)

chore-000: add readme for the backend

---

README.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

#5 added my username

---

docs/pull_request_template.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Task #5 

TASK-5: update documentation for pull request template

---

README.md

The README file now displays the correct Github URL for team member "Julien Xu"

Updated Github URL of "Julien Xu"

---

README.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

#5 update the description of the README

---

docs/account_template.md
docs/image_template.md

CHORE-5: setup env for backend

---

README.md

Updated the readme
```
```
Issue reference: #5 

TASK-5: add technologies in the readme

---

docs/pull_request_template.md

TASK-5: Update pull request template

---

README.md

TASK-5: Changed backend technology in the readme

---

.travis.yml
frontend/src/App.js
frontend/src/App.test.js

Implement a travis continuous integration for the application
Issue reference: #27 
```
```

FEAT-#27: add a travis script for the react frontend and backend

---

frontend/src/components/drawer.jsx
frontend/src/components/search/searchPage.jsx

Implement a search page in the ui
Issue reference: #45 #7 
```
```

Task 45/implement search page

---

backend/resources/routes.py
backend/resources/users.py
docs/api_doc.md

I implemented the login api route in the backend.
Issue reference: #46 
```
```

TASK-#46: login api route

---

backend/app.py
backend/requirements.txt
frontend/package-lock.json
frontend/src/components/drawer.jsx

Implement login form and connection between frontend and backend
Issue reference: #54 #35 
```
```

TASK-#54: add a fetch between backend and frontend to login

---

backend/resources/routes.py
backend/resources/users.py
docs/API_docs/FollowUserAPI.md
docs/API_docs/LoginAPI.md
docs/API_docs/SearchUserAPI.md

I implemented the search api
It is a get request that returns all the users without the requesting user.
Look at documentation for more info
Issue reference: #62 
```
```

Task 62/search bar api

---

backend/database/models.py
backend/requirements.txt
backend/resources/routes.py
backend/resources/users.py

Implemented the default page api route that returns a list of pictures
Issue reference: #64 
```
```

TASK-#64: Added get api for default page

---

backend/resources/users.py
frontend/src/components/drawer.jsx
frontend/src/components/search/searchPage.jsx
frontend/src/components/user/userPage.jsx

disable follow button when following already
Issue reference: #7 
```
```

Chore 07/disable follow button

---

backend/Procfile
backend/heroku.py
backend/requirements.txt

Implement correct files for the heroku server to run
Issue reference: #74 
```
```

Task 74/implement heroku server

---

frontend/src/components/drawer.jsx
frontend/src/components/search/searchPage.jsx
frontend/src/components/user/userPage.jsx
frontend/src/config.js

point to production api
```
```

Chore 007/production api

---

frontend/src/components/drawer.jsx

change api from dev to prod
```
```

CHORE-000: change api from dev to prod

---

backend/resources/users.py
frontend/src/components/search/searchPage.jsx

update list when search
```
```

Chore 0001/update list when search

---

frontend/src/components/drawer.jsx

CHORE-002: add tracking

---

backend/resources/users.py

CHORE-002:fixed whitespace username bug

---

frontend/src/components/drawer.jsx

CHORE-005: add tracking

---

backend/resources/routes.py
backend/resources/users.py
docs/API_docs/UnfollowUserAPI.md

Task 86/implement unfollow api

---

backend/database/models.py
backend/resources/pictures.py
backend/resources/users.py

TASK-#86: Added field nb_pictures to user

---

frontend/src/components/drawer.jsx
frontend/src/components/search/searchPage.jsx
frontend/src/components/user/userPage.jsx

create a user page
Issue reference: #44 
```
```

Task #44/create a user page

---

backend/database/models.py
backend/resources/routes.py
backend/resources/users.py
docs/API_docs/UpdateBioAPI.md

I implemented an api route to update the bio of a user
Issue reference: #90
```
```

Task 90/update bio api

---

frontend/src/components/postImage/uploadPage.jsx

CHORE-001: add disable to button

---

frontend/src/components/drawer.jsx
frontend/src/components/images/ImageListPage.jsx
frontend/src/components/images/imageBox.jsx
frontend/src/components/postImage/uploadPage.jsx
frontend/src/components/search/searchPage.jsx
frontend/src/components/user/userPage.jsx

Post image (only description with mock image)
Comment on a picture
User feed and user image
Issue reference: #100 
```
```

TASK-#100: add update to feed and post picture

---

frontend/src/components/drawer.jsx
frontend/src/components/images/ImageListPage.jsx

CHORE-007: add reload button for feed

---

backend/resources/users.py
docs/API_docs/FeedAPI.md
docs/API_docs/SearchUserAPI.md
docs/API_docs/UserInfoAPI.md

Chore 003/get comment user

---

frontend/src/components/images/imageBox.jsx

CHORE-005: add number of comments

---

backend/database/models.py
backend/resources/pictures.py
backend/resources/routes.py
docs/API_docs/UpdateLikeApi.md
frontend/src/components/drawer.jsx
frontend/src/components/images/imageBox.jsx
frontend/src/components/postImage/uploadPage.jsx
frontend/src/components/user/userPage.jsx

implement like and dislike
Issue reference: #103 
```
```

Us 103/implement like dislike

---

frontend/src/components/drawer.jsx
frontend/src/components/home/homepage.jsx
frontend/src/components/images/ImageListPage.jsx

fix feed not updating
Issue reference: #111 
```
```

BUG-#111: fix feed not updating

---

frontend/src/components/drawer.jsx
frontend/src/components/images/imageBox.jsx
frontend/src/components/postImage/uploadPage.jsx

implement image upload
Issue reference: #6 
```
```

FEAT-#6: implement image upload

---

frontend/src/components/images/ImageListPage.jsx
frontend/src/components/images/imageBox.jsx
frontend/src/components/postImage/uploadPage.jsx

change ui look for image box
Issue reference: #108 
```
```

CHORE-#108: change font of ui box and remove unecessary log

---

frontend/src/components/home/homepage.jsx

fix reload button in homepage 
Issue reference: #115 
```
```

BUG-#115: implement reload button

---

backend/resources/pictures.py

Issue reference: #115 
```
```

BUG#115: Fixed own picture in queue

---

frontend/src/components/images/imageBox/Comment.jsx

make user in comment in bold
```
```

CHORE-001: make user in comment in bold

---

frontend/src/components/home/homepage.jsx
frontend/src/components/images/ImageListPage.jsx

CHORE-007: refactor ui

---

README.md

TASK-5: Updating the list of additional features

---

docs/Test_Cases.md

Adding test cases
Issue reference: #129 
```
```

TASK-#129: write test cases in doc
